### Get task
GET {{baseUrl}}/task/25 HTTP/1.1
Authorization: Bearer {{token}}

### Create task
POST {{baseUrl}}/task HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Task 7",
    "description": "Task 2 description",
    "categoryId": 52,
    "labels": [
        71, 72
    ],
    "duration": 2,
    "priority": 2,	
    "dueDate": "2023-03-20"
}

### Get all task
GET {{baseUrl}}/task HTTP/1.1
Authorization: Bearer {{token}}

### Update task status
PATCH {{baseUrl}}/task/25/status HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": "IN_PROGRESS"
}

### Update task
PATCH {{baseUrl}}/task/25 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "labels": [
        11
    ]
}

### Auto schedule task
GET {{baseUrl}}/task/auto-schedule?hours=11 HTTP/1.1
Authorization: Bearer {{token}}