### Login
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "thanhnhan@gmail.com",
    "password": "nHAN_2947"
}

### Register
POST {{baseUrl}}/auth/register HTTP/1.1
content-type: application/json

{
    "email": "thanhnhan@gmail.com",
    "password": "nHAN_2947",
    "confirmPassword": "nHAN_2947",
    "username": "nhan2947",
    "name": "Thanh Nhan"
}